[package]
name = "armagetronapi"
version = "0.1.0"
edition = "2024"

# [[example]]
# name = "hello_world"
# path = "examples/hello_world.rs"

[dependencies]
chrono = "0.4.42"
encoding_rs = "0.8.35"
itertools = "0.14.0"
